Repository market-sentiment-analyzer-tool/msat, pull requests merged in 2024-11, with the labels that each got.

#44 Implemented manual Yahoo Scraper
  db/data.sql
  db/data/yahoo/yahoo_aapl_data.sql
  db/data/yahoo/yahoo_amzn_data.sql
  db/data/yahoo/yahoo_goog_data.sql
  db/data/yahoo/yahoo_msft_data.sql
  db/data/yahoo/yahoo_nvda_data.sql
  db/initializeDatabase.sh
  db/schema.sql
  db/yahooDumpData.sh
  db/yahooStockInfo.json
  db/yahooUpdateDatabase.sh
  scrapers/yahooScraper.py
Labels: bug, enhancement

#47 Implemented QA for Yahoo
  tests/test_database.py
  tests/test_general.py
  tests/test_yahooScraper.py
  ui/package-lock.json
Labels: bug, enhancement

#52 Locust testing
  tests/test_api.py
Labels: enhancement

#59 Readme final release
  README.md
  api/README.md
  db/README.md
  docs/architecture-diagram.png
  docs/deployment-diagram.png
  scrapers/README.md
  tests/README.md
  ui/README.md
  vaderSentiment/README.md
Labels: documentation

#60 Minor fixes UI
  ui/package-lock.json
  ui/src/App.css
  ui/src/App.js
  ui/src/InfoTable.css
  ui/src/InfoTable.js
  ui/src/PieChart.js
  ui/src/SentimentPage.css
  ui/src/SentimentPage.js
  ui/src/SentimentRange.css
  ui/src/SentimentRange.js
  ui/src/WeightInput.js
  ui/src/index.css
  ui/src/index.js
Labels: bug, enhancement

#62 QA for UI with Selenium
  requirements.txt
  tests/test_userInterface.py
Labels: enhancement
